[package]
name = "are_you_the_one"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# bevy = "0.6.1"
rand = "0.8.5"
env_logger = "0.9.0"
log = "0.4.16"
plotters = "0.3.1"
simple-logging = "2.0.2"